etcaterva/eas-backend

- eas/api/serializers.py
- eas/api/tests/test_serializers.py
- eas/api/views.py
Add `private_id` to the serializer to it shows up in swagger. Rather than adding it dynamically to the draws that have the owner the code will instead remove it when the user is not the owner of the draw.
Closes #13
> Expose draws `private_id` in the swagger docs

- eas/api/models.py
- eas/api/tests/test_models.py
The schema already defines the result value type as a list of integers and this will allow the future enhancement of allowing to generate multiple results in a single toss.
> Update random number to generate results as a list

- eas/api/models.py
- eas/api/serializers.py
- eas/api/tests/int/common.py
- eas/api/views.py
- swagger.yaml
Support clients to schedule a toss rather than requesting an immediate one. The toss is resolved at retrieve time as a compromise to keep the implementation simple and not having to add other background processes.
Closes #2
> Add support for scheduling a toss

- eas/api/tests/int/test_raffle.py
- eas/api/views.py
- swagger.yaml
This will be used for the raffles where the list of participants is not fixed since the beginning and are added after its creation.
Closes #24
> Add endpoint to add participants to an existing raffle

- README.md
- eas/api/urls.py
- eas/api/views.py
- eas/settings/base.py
Remove all code that generates the UI from the source code.
As we now have the swagger file we should just server the swagger ui
from the file.
Closes #16
> Remove swagger generator

- eas/settings/prod.py
We have configured all domains in the base, as we are allowing everything within a subdomain there is no need to have settings per environment.
> Remove `ALLOWED_HOSTS` from settings.prod

- swagger.yaml
Probably from a copy paste from the groups draw, the type is of the result value element was set to an array of arrays.
Fixed to just be an array.
Closes #42
> Fix return type of letter and random number

- eas/api/serializers.py
- eas/api/tests/int/test_random_number.py
As the values are defaulted in the API we did not check that they can be not present at the time we validate them in the serializer.
> Fix internal error when some random_number args are not provided

- requirements/prod.txt
The psycopg2 is branching into two flavors, sdist and wheel. Whilst both were provided within the same package before, the wheel is now only present in `psycopg2`. This commit moves the project to the binary package as it is more convenient. There are reports of the binary segfaulting under certain conditions, should those arise in the project we should move to the sdist and add the system dependency on the library it needs to compile.
For further info, check:
http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/
or issue #38
Closes #38
> Move requirement to `psycopg2-binary` from `psycopg2`

- eas/settings/dev.py
- eas/settings/prod.py
- requirements/base.txt
Configure sentry to report errors to the framework that will trigger emails with information about the incident. An environment variable is needed to configure sentry, it has to be set on startup.
Closes #10
> Configure Sentry to report errors

- swagger.yaml
This needs no be overriden in the clients
> Make explicit that basePath is not used

- .travis.yml
The CI was wrongly running makemigrations rather than running them.
The migrations should be available, makemigration might have make the
tests pass in the past because they were not run.
> ci: Check for pending migrations rather than running them

- eas/settings/base.py
Ignore the exception that can be raised if the host is unable to find
the local IP. This can happen if for example gethostname returns a name
that is mapped to an IPv6 address, which is not supported by
gethostbyname.
> Don't hard fail if unable to get local IP

- eas/api/serializers.py
- eas/api/tests/int/test_letter.py
If an user specifies that results can be repeated we can remove
altogether the upper bound on the number of results.
> Fix number of results limit in Letter draw

- eas/api/serializers.py
This will prevent generating an internal error if an user requests a
million random letters.
> Set an arbitrary value for Letter number_of_results

- eas/api/models.py
- eas/api/tests/int/test_raffle.py
- eas/api/views.py
We will just repeat the participants as that is the most intuitive
action for organizers.
Closes https://github.com/etcaterva/eas-frontend/issues/193
> Allow toss a raffle with insufficient results

- eas/settings/prod.py
We can enable this if we ever need it.
Closes https://github.com/etcaterva/eas-backend/issues/77
If we ever need the admin panel we just need to re-enable this and create a user.
> Disable admin in production

- eas/api/error_handler.py
- eas/api/tests/int/test_secret_santa.py
- eas/api/views.py
- eas/settings/base.py
This will facilitate consuming them on the frontend.
closes #95
> Translate error message to make them easier to consume

- eas/api/serializers.py
- eas/api/tests/int/test_random_number.py
That's the way we expect it to behave, and its already how [randint](https://docs.python.org/3/library/random.html#random.randint) works, including both the initial and end value.
I image that the use case for this is generating a shuffled list of numbers from A to B, which I guess is a valid use case
Please review if the tests make sense
> Include range_min and range_max in RandomNumber validation

- .coveragerc
- README.md
- celery-task.py
- eas/api/email.py
- eas/api/serializers.py
- eas/api/views.py
- eas/settings/base.py
- requirements/base.txt
Use celery to send emails asyncronously. This will allow to handle
secret santa draws with a high number of participants. Without this, the
server waits synchronously for the emails to be sent, timesouts and
harakiri will finalize the web backend process.
Closes #101
> Send emails asynchronously

- eas/api/templates/secret-santa-result-mail.html
This will prevent google from thinking the email is a quote from the
previous one, hiding new mails.
Closes #129
> Include date in amigo invisible date

- eas/api/views.py
- swagger.yaml
Not completed, I'm still getting the following error when hitting the preview endpoint:
GET: `/api/instagram-preview/?post_url=https%253A%252F%252Fwww.instagram.com%252Fp%252FChVkm42jYdD`
```
[2022-09-18T19:13:59.027] ERROR django.request log.py:224 | Internal Server Error: /api/instagram-preview/
Traceback (most recent call last):
File "/Users/davidnaranjo/opt/anaconda3/envs/eas/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/Users/davidnaranjo/opt/anaconda3/envs/eas/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/davidnaranjo/opt/anaconda3/envs/eas/lib/python3.8/site-packages/django/views/decor …
```
> Fix post_url param in swagger

- requirements/local.txt
This will prevent the CI from sporadically failing.
> Pin local dev requirements

- eas/api/tests/int/test_instagram.py
This will save some API calls.
> tests: Don't clear the cache on end to end tests

- eas/settings/base.py
This will be removed in Django 5 and is now spewing warnings.
> Remove deprecated setting

- eas/api/models.py
- eas/api/views.py
Calling this method will trigger a call to fetch the comments of a post for the instagram post, this will consume our quota.
Closes #173
> Call `resolve_scheduled_results` only if necessary

- eas/api/views.py
This will log the actual data rather than the object id, which is more useful when debugging issues.
> Log draw data, not the object

- .github/workflows/test-and-deploy.yml
```
[set-vars](https://github.com/etcaterva/eas-backend/actions/runs/6983666903/job/19005187829#step:2:15)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
[Lint & Test (3.8)](https://github.com/etcaterva/eas-backend/actions/runs/6983666903/job/19005187702)
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-python@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
[Validate swagger file](https://github.com/etcaterva/eas-backend/actions/runs/69836 …
```
> Fix deprecated warnings on github actions

- eas/api/views.py
If a post is closed after a toss have been generated and the user asks for a retoss we should return a valid error.
Closes #221
> Handle retoss on closed posts

- swagger.yaml
No changes in the API, this is just to make the generated SDK have better naming
> Update swagger spec for retoss

- eas/api/views.py
- eas/settings/prod.py
Reduce the amount of log we keep and remove the most noisy log line. We can see the actual result by hitting the API if needed.
> Reduce logging output and files kept

- eas/api/secret_santa.py
- eas/api/views.py
- pyproject.toml
Prevent flaky failures from invalid combinations.
> Implement secret santa with backtracking
