etcaterva/eas-backend

eas/api/apps.py
eas/api/models.py
eas/api/serializers.py
eas/api/tests/factories.py
eas/api/tests/int/common.py
eas/api/tests/int/test_raffle.py
eas/api/tests/int/test_random_number.py
eas/api/urls.py
eas/api/views.py
eas/settings.py

Adds a new draw that allows to create a raffle and give prizes to participants.
This commit has other unrelated changes though. :(
Closes #5

Add raffle draw

---

eas/api/views.py
eas/settings/base.py

Add basic logging configuration to the server to help troubleshooting issues.
Closes #20

Add logging traces and configuration

---

swagger.yaml

We are already using 3.0 attributes like 'nullable'

Move swaggerfile to openapi3 specification

---

.pylintrc
eas/api/models.py
eas/api/serializers.py
eas/api/tests/factories.py
eas/api/tests/int/common.py
eas/api/tests/int/test_lottery.py
eas/api/urls.py
eas/api/views.py
swagger.yaml

New draw type: lottery

---

eas/api/models.py
eas/api/serializers.py
eas/api/tests/factories.py
eas/api/tests/int/test_groups.py
eas/api/urls.py
eas/api/views.py
swagger.yaml

The Groups draw allows to group a list of participants in groups given
the number of groups to generate.

 Add new draw: groups

---

eas/api/models.py
eas/api/serializers.py
eas/api/tests/factories.py
eas/api/tests/int/test_spinner.py
eas/api/urls.py
eas/api/views.py
swagger.yaml

A simple draw that returns the angle of the spinner.

Add spinner draw

---

eas/api/models.py
eas/api/serializers.py
eas/api/tests/factories.py
eas/api/tests/int/test_coin.py
eas/api/urls.py
eas/api/views.py
swagger.yaml

The new draw can either return coin or tail.
The result type is an array due to issues in the framework serializing bare strings.

Add new draw: coin

---

eas/settings/base.py

This is a whitelist of the hosts that the server will accept.
Closes #39

Add known host names to `ALLOWED_HOSTS`

---

requirements/base.txt

Upgrade django version as the current one contains a security vulnerability.

Upgrade django version

---

eas/api/tests/int/test_raffle.py
eas/api/views.py

This kind of draws that allow people to sign up on a later stage should be allowed to be created even when there are not enough participants.
Closes #54

Allow creating a scheduled raffle without participants

---

eas/settings/prod.py

Just copied the configuration we had in eas2, but kept the current format and datefmt.

Configure logging to file

---

requirements/base.txt
requirements/local.txt

Upgrade requirements to the latest version

---

eas/api/views.py

I assume this change is a consequence of upgrading
to a newer pylint.

Change pylint disable flag to ignore unused args

---

eas/api/migrations/0002_auto_20191005_1516.py

The unique constraint should not have included the "name" column.

Update migration file to reflect models status

---

pytest.ini
requirements/local.txt

Add new dependency to run tests with pytest.

Run tests with pytest

---

requirements/base.txt
requirements/local.txt

Dateutil is now used by our purge command.

Add a requirement in dateutil

---

eas/api/serializers.py

This removes the need to commit on every new participant.
Closes #94

Use bulk create API

---

eas/api/email.py
eas/api/templates/secret-santa-result-mail.html
eas/api/views.py
requirements/local.txt

Improve secret santa email

---

eas/api/management/commands/backup.py
eas/api/tests/int/common.py
eas/api/tests/int/test_backup.py
eas/api/tests/int/test_raffle.py
eas/api/views.py

This includes all draws, not just the public ones.

Add new command to backup based on time deltas

---

eas/api/management/commands/backup.py
eas/api/tests/factories.py
eas/api/tests/int/test_backup.py

Backup secret santa results and payment details

---

requirements/prod.txt

Avoid going to 2.9.x, to not break things right now

Upgrade psycopg2-binary to a newer version

---

eas/api/instagram.py
eas/api/tests/int/test_instagram.py
eas/api/views.py
eas/settings/base.py

Improve caching and return 404 on missing post

---

eas/api/instagram.py
eas/api/models.py
eas/api/tests/int/test_instagram.py

This should result in a lower number of API calls.

Lazily fetch comments from instagram

---

eas/api/instagram.py
eas/api/models.py
eas/api/tests/int/test_instagram.py
eas/api/views.py
requirements/base.orig.txt
requirements/base.txt

The requests_cache was caching based on url, and we need a policy based on the post URL which is part of the parameters.

Use a custom cache for datalama

---

eas/api/instagram.py
eas/api/models.py
eas/api/tests/int/test_instagram.py
swagger.yaml

This will facilitate linking to the original comment on the result.

Add Instagram comment id to result

---

eas/api/instagram/__init__.py

This will facilitate debugging.

Log restrictions for fetching comments

---

eas/api/instagram/lamadava.py

This will allow knowing when we have cache misses.

Log requests sent to lamadava

---

eas/api/models.py
eas/api/serializers.py
eas/api/tests/int/test_instagram.py
eas/api/views.py
swagger.yaml

This is a common request for instagram raffles.

instagram: Add an option to regenerate a single comment

---

.github/workflows/test-and-deploy.yml

Add github action to validate swagger file

---

eas/api/instagram/lamadava.py

Log failed requests as text

---

eas/api/amazonsqs.py
eas/settings/base.py
eas/settings/local.py
eas/settings/prod.py

Update to use new AWS ids

---

requirements/local.txt

To make sure this works with the version of pip-tools.

Pin version of pip

---

swagger.yaml

swagger: Update secret-santa-admin URL to post

---

eas/api/instagram/lamadava.py

Log lamadava response

---

eas/api/instagram/lamadava.py

Lamadava raises an error if comments are disabled.

Return no comments when we get NotFoundError

---

eas/api/models.py
eas/api/tests/int/test_tournament.py
swagger.yaml

This is more generic and will allow us to make matches of multiple participants.

Use an array for the list of participants

---

eas/api/serializers.py

We have seen users doing draws with more than 200.

Allow user to specify up to 2000 items

---

eas/api/instagram/lamadava.py

The GQL API is temporarily unavailable.

Migrate lamadava from gql to v2 API

---

eas/api/tests/int/test_lamatok.py
eas/api/tiktok/lamatok.py

Handle private tiktok videos

---

eas/settings/prod.py

Keep 2GB of info logs

---

eas/api/views.py
swagger.yaml

This will generate an additional email that can be used to find the admin panel.

Include admin email and private id

---

swagger.yaml

To improve the generated models in Typescript

Refactor swagger spec

---

eas/api/views.py

We are moving towards "plans" where basic will include both certification and no ads for 2€, whilst a premium plan is raising to 7€.

Update payment amount to the new values
